"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateSecureToken = exports.verifyPassword = exports.hashPassword = exports.decryptApiKey = exports.encryptApiKey = exports.decryptData = exports.encryptData = exports.generateEncryptionKey = exports.retry = exports.hashString = exports.createCacheKey = exports.isNonNegativeNumber = exports.isPositiveNumber = exports.isValidNumber = exports.validateUrl = exports.validateEmail = exports.validateApiKey = exports.kebabCase = exports.camelCase = exports.capitalize = exports.truncate = exports.slugify = exports.standardDeviation = exports.median = exports.average = exports.unique = exports.sortBy = exports.groupBy = exports.chunk = exports.calculateConfidenceScore = exports.getRiskLevel = exports.calculateRiskScore = exports.calculateNetProfit = exports.calculateBrokerFees = exports.calculateTaxes = exports.calculateBreakEvenPrice = exports.calculateROI = exports.calculateProfit = exports.calculateProfitMargin = exports.addHours = exports.addDays = exports.isDateExpired = exports.formatRelativeTime = exports.formatDate = exports.sleep = exports.formatDuration = exports.formatPercentage = exports.formatNumber = exports.formatISK = exports.formatCurrency = void 0;
exports.validatePassword = exports.validateEveApiKey = exports.validateDataSafe = exports.validateData = exports.notificationSchema = exports.userProfileSchema = exports.analysisContextSchema = exports.executedTradeSchema = exports.tradingSuggestionSchema = exports.tradingPlanParamsSchema = exports.alertRuleSchema = exports.watchlistItemSchema = exports.historicalDataRequestSchema = exports.marketDataRequestSchema = exports.marketOrderSchema = exports.eveCharacterSchema = exports.eveApiKeySchema = exports.userPreferencesSchema = exports.userRegistrationSchema = exports.userCredentialsSchema = exports.iskAmountSchema = exports.eveTypeIdSchema = exports.eveRegionIdSchema = exports.eveCharacterIdSchema = exports.nonNegativeNumberSchema = exports.positiveNumberSchema = exports.uuidSchema = exports.passwordSchema = exports.emailSchema = exports.sanitizeErrorForLogging = exports.getRetryDelay = exports.isRetryableError = exports.createValidationError = exports.formatErrorResponse = exports.ServiceUnavailableError = exports.InternalServerError = exports.DatabaseErrorClass = exports.RateLimitError = exports.AiProviderErrorClass = exports.EsiApiError = exports.ConflictError = exports.NotFoundError = exports.ApiKeyValidationError = exports.ValidationErrorClass = exports.TokenExpiredError = exports.AuthorizationError = exports.AuthenticationError = exports.AppError = exports.verifyHmacSignature = exports.createHmacSignature = void 0;
exports.createErrorLogger = exports.createRequestLogger = exports.HealthMonitor = exports.getLogger = exports.initializeLogger = exports.createLogger = exports.AppLogger = exports.validatePagination = exports.paginationSchema = exports.createUpdateSchema = exports.validateEveTypeId = exports.validateEveRegionId = exports.validateEveCharacterId = exports.validateIskAmount = void 0;
__exportStar(require("./types"), exports);
__exportStar(require("./constants"), exports);
var utils_1 = require("./utils");
Object.defineProperty(exports, "formatCurrency", { enumerable: true, get: function () { return utils_1.formatCurrency; } });
Object.defineProperty(exports, "formatISK", { enumerable: true, get: function () { return utils_1.formatISK; } });
Object.defineProperty(exports, "formatNumber", { enumerable: true, get: function () { return utils_1.formatNumber; } });
Object.defineProperty(exports, "formatPercentage", { enumerable: true, get: function () { return utils_1.formatPercentage; } });
Object.defineProperty(exports, "formatDuration", { enumerable: true, get: function () { return utils_1.formatDuration; } });
Object.defineProperty(exports, "sleep", { enumerable: true, get: function () { return utils_1.sleep; } });
Object.defineProperty(exports, "formatDate", { enumerable: true, get: function () { return utils_1.formatDate; } });
Object.defineProperty(exports, "formatRelativeTime", { enumerable: true, get: function () { return utils_1.formatRelativeTime; } });
Object.defineProperty(exports, "isDateExpired", { enumerable: true, get: function () { return utils_1.isDateExpired; } });
Object.defineProperty(exports, "addDays", { enumerable: true, get: function () { return utils_1.addDays; } });
Object.defineProperty(exports, "addHours", { enumerable: true, get: function () { return utils_1.addHours; } });
Object.defineProperty(exports, "calculateProfitMargin", { enumerable: true, get: function () { return utils_1.calculateProfitMargin; } });
Object.defineProperty(exports, "calculateProfit", { enumerable: true, get: function () { return utils_1.calculateProfit; } });
Object.defineProperty(exports, "calculateROI", { enumerable: true, get: function () { return utils_1.calculateROI; } });
Object.defineProperty(exports, "calculateBreakEvenPrice", { enumerable: true, get: function () { return utils_1.calculateBreakEvenPrice; } });
Object.defineProperty(exports, "calculateTaxes", { enumerable: true, get: function () { return utils_1.calculateTaxes; } });
Object.defineProperty(exports, "calculateBrokerFees", { enumerable: true, get: function () { return utils_1.calculateBrokerFees; } });
Object.defineProperty(exports, "calculateNetProfit", { enumerable: true, get: function () { return utils_1.calculateNetProfit; } });
Object.defineProperty(exports, "calculateRiskScore", { enumerable: true, get: function () { return utils_1.calculateRiskScore; } });
Object.defineProperty(exports, "getRiskLevel", { enumerable: true, get: function () { return utils_1.getRiskLevel; } });
Object.defineProperty(exports, "calculateConfidenceScore", { enumerable: true, get: function () { return utils_1.calculateConfidenceScore; } });
Object.defineProperty(exports, "chunk", { enumerable: true, get: function () { return utils_1.chunk; } });
Object.defineProperty(exports, "groupBy", { enumerable: true, get: function () { return utils_1.groupBy; } });
Object.defineProperty(exports, "sortBy", { enumerable: true, get: function () { return utils_1.sortBy; } });
Object.defineProperty(exports, "unique", { enumerable: true, get: function () { return utils_1.unique; } });
Object.defineProperty(exports, "average", { enumerable: true, get: function () { return utils_1.average; } });
Object.defineProperty(exports, "median", { enumerable: true, get: function () { return utils_1.median; } });
Object.defineProperty(exports, "standardDeviation", { enumerable: true, get: function () { return utils_1.standardDeviation; } });
Object.defineProperty(exports, "slugify", { enumerable: true, get: function () { return utils_1.slugify; } });
Object.defineProperty(exports, "truncate", { enumerable: true, get: function () { return utils_1.truncate; } });
Object.defineProperty(exports, "capitalize", { enumerable: true, get: function () { return utils_1.capitalize; } });
Object.defineProperty(exports, "camelCase", { enumerable: true, get: function () { return utils_1.camelCase; } });
Object.defineProperty(exports, "kebabCase", { enumerable: true, get: function () { return utils_1.kebabCase; } });
Object.defineProperty(exports, "validateApiKey", { enumerable: true, get: function () { return utils_1.validateApiKey; } });
Object.defineProperty(exports, "validateEmail", { enumerable: true, get: function () { return utils_1.validateEmail; } });
Object.defineProperty(exports, "validateUrl", { enumerable: true, get: function () { return utils_1.validateUrl; } });
Object.defineProperty(exports, "isValidNumber", { enumerable: true, get: function () { return utils_1.isValidNumber; } });
Object.defineProperty(exports, "isPositiveNumber", { enumerable: true, get: function () { return utils_1.isPositiveNumber; } });
Object.defineProperty(exports, "isNonNegativeNumber", { enumerable: true, get: function () { return utils_1.isNonNegativeNumber; } });
Object.defineProperty(exports, "createCacheKey", { enumerable: true, get: function () { return utils_1.createCacheKey; } });
Object.defineProperty(exports, "hashString", { enumerable: true, get: function () { return utils_1.hashString; } });
Object.defineProperty(exports, "retry", { enumerable: true, get: function () { return utils_1.retry; } });
Object.defineProperty(exports, "generateEncryptionKey", { enumerable: true, get: function () { return utils_1.generateEncryptionKey; } });
Object.defineProperty(exports, "encryptData", { enumerable: true, get: function () { return utils_1.encryptData; } });
Object.defineProperty(exports, "decryptData", { enumerable: true, get: function () { return utils_1.decryptData; } });
Object.defineProperty(exports, "encryptApiKey", { enumerable: true, get: function () { return utils_1.encryptApiKey; } });
Object.defineProperty(exports, "decryptApiKey", { enumerable: true, get: function () { return utils_1.decryptApiKey; } });
Object.defineProperty(exports, "hashPassword", { enumerable: true, get: function () { return utils_1.hashPassword; } });
Object.defineProperty(exports, "verifyPassword", { enumerable: true, get: function () { return utils_1.verifyPassword; } });
Object.defineProperty(exports, "generateSecureToken", { enumerable: true, get: function () { return utils_1.generateSecureToken; } });
Object.defineProperty(exports, "createHmacSignature", { enumerable: true, get: function () { return utils_1.createHmacSignature; } });
Object.defineProperty(exports, "verifyHmacSignature", { enumerable: true, get: function () { return utils_1.verifyHmacSignature; } });
Object.defineProperty(exports, "AppError", { enumerable: true, get: function () { return utils_1.AppError; } });
Object.defineProperty(exports, "AuthenticationError", { enumerable: true, get: function () { return utils_1.AuthenticationError; } });
Object.defineProperty(exports, "AuthorizationError", { enumerable: true, get: function () { return utils_1.AuthorizationError; } });
Object.defineProperty(exports, "TokenExpiredError", { enumerable: true, get: function () { return utils_1.TokenExpiredError; } });
Object.defineProperty(exports, "ValidationErrorClass", { enumerable: true, get: function () { return utils_1.ValidationErrorClass; } });
Object.defineProperty(exports, "ApiKeyValidationError", { enumerable: true, get: function () { return utils_1.ApiKeyValidationError; } });
Object.defineProperty(exports, "NotFoundError", { enumerable: true, get: function () { return utils_1.NotFoundError; } });
Object.defineProperty(exports, "ConflictError", { enumerable: true, get: function () { return utils_1.ConflictError; } });
Object.defineProperty(exports, "EsiApiError", { enumerable: true, get: function () { return utils_1.EsiApiError; } });
Object.defineProperty(exports, "AiProviderErrorClass", { enumerable: true, get: function () { return utils_1.AiProviderError; } });
Object.defineProperty(exports, "RateLimitError", { enumerable: true, get: function () { return utils_1.RateLimitError; } });
Object.defineProperty(exports, "DatabaseErrorClass", { enumerable: true, get: function () { return utils_1.DatabaseError; } });
Object.defineProperty(exports, "InternalServerError", { enumerable: true, get: function () { return utils_1.InternalServerError; } });
Object.defineProperty(exports, "ServiceUnavailableError", { enumerable: true, get: function () { return utils_1.ServiceUnavailableError; } });
Object.defineProperty(exports, "formatErrorResponse", { enumerable: true, get: function () { return utils_1.formatErrorResponse; } });
Object.defineProperty(exports, "createValidationError", { enumerable: true, get: function () { return utils_1.createValidationError; } });
Object.defineProperty(exports, "isRetryableError", { enumerable: true, get: function () { return utils_1.isRetryableError; } });
Object.defineProperty(exports, "getRetryDelay", { enumerable: true, get: function () { return utils_1.getRetryDelay; } });
Object.defineProperty(exports, "sanitizeErrorForLogging", { enumerable: true, get: function () { return utils_1.sanitizeErrorForLogging; } });
Object.defineProperty(exports, "emailSchema", { enumerable: true, get: function () { return utils_1.emailSchema; } });
Object.defineProperty(exports, "passwordSchema", { enumerable: true, get: function () { return utils_1.passwordSchema; } });
Object.defineProperty(exports, "uuidSchema", { enumerable: true, get: function () { return utils_1.uuidSchema; } });
Object.defineProperty(exports, "positiveNumberSchema", { enumerable: true, get: function () { return utils_1.positiveNumberSchema; } });
Object.defineProperty(exports, "nonNegativeNumberSchema", { enumerable: true, get: function () { return utils_1.nonNegativeNumberSchema; } });
Object.defineProperty(exports, "eveCharacterIdSchema", { enumerable: true, get: function () { return utils_1.eveCharacterIdSchema; } });
Object.defineProperty(exports, "eveRegionIdSchema", { enumerable: true, get: function () { return utils_1.eveRegionIdSchema; } });
Object.defineProperty(exports, "eveTypeIdSchema", { enumerable: true, get: function () { return utils_1.eveTypeIdSchema; } });
Object.defineProperty(exports, "iskAmountSchema", { enumerable: true, get: function () { return utils_1.iskAmountSchema; } });
Object.defineProperty(exports, "userCredentialsSchema", { enumerable: true, get: function () { return utils_1.userCredentialsSchema; } });
Object.defineProperty(exports, "userRegistrationSchema", { enumerable: true, get: function () { return utils_1.userRegistrationSchema; } });
Object.defineProperty(exports, "userPreferencesSchema", { enumerable: true, get: function () { return utils_1.userPreferencesSchema; } });
Object.defineProperty(exports, "eveApiKeySchema", { enumerable: true, get: function () { return utils_1.eveApiKeySchema; } });
Object.defineProperty(exports, "eveCharacterSchema", { enumerable: true, get: function () { return utils_1.eveCharacterSchema; } });
Object.defineProperty(exports, "marketOrderSchema", { enumerable: true, get: function () { return utils_1.marketOrderSchema; } });
Object.defineProperty(exports, "marketDataRequestSchema", { enumerable: true, get: function () { return utils_1.marketDataRequestSchema; } });
Object.defineProperty(exports, "historicalDataRequestSchema", { enumerable: true, get: function () { return utils_1.historicalDataRequestSchema; } });
Object.defineProperty(exports, "watchlistItemSchema", { enumerable: true, get: function () { return utils_1.watchlistItemSchema; } });
Object.defineProperty(exports, "alertRuleSchema", { enumerable: true, get: function () { return utils_1.alertRuleSchema; } });
Object.defineProperty(exports, "tradingPlanParamsSchema", { enumerable: true, get: function () { return utils_1.tradingPlanParamsSchema; } });
Object.defineProperty(exports, "tradingSuggestionSchema", { enumerable: true, get: function () { return utils_1.tradingSuggestionSchema; } });
Object.defineProperty(exports, "executedTradeSchema", { enumerable: true, get: function () { return utils_1.executedTradeSchema; } });
Object.defineProperty(exports, "analysisContextSchema", { enumerable: true, get: function () { return utils_1.analysisContextSchema; } });
Object.defineProperty(exports, "userProfileSchema", { enumerable: true, get: function () { return utils_1.userProfileSchema; } });
Object.defineProperty(exports, "notificationSchema", { enumerable: true, get: function () { return utils_1.notificationSchema; } });
Object.defineProperty(exports, "validateData", { enumerable: true, get: function () { return utils_1.validateData; } });
Object.defineProperty(exports, "validateDataSafe", { enumerable: true, get: function () { return utils_1.validateDataSafe; } });
Object.defineProperty(exports, "validateEveApiKey", { enumerable: true, get: function () { return utils_1.validateEveApiKey; } });
Object.defineProperty(exports, "validatePassword", { enumerable: true, get: function () { return utils_1.validatePassword; } });
Object.defineProperty(exports, "validateIskAmount", { enumerable: true, get: function () { return utils_1.validateIskAmount; } });
Object.defineProperty(exports, "validateEveCharacterId", { enumerable: true, get: function () { return utils_1.validateEveCharacterId; } });
Object.defineProperty(exports, "validateEveRegionId", { enumerable: true, get: function () { return utils_1.validateEveRegionId; } });
Object.defineProperty(exports, "validateEveTypeId", { enumerable: true, get: function () { return utils_1.validateEveTypeId; } });
Object.defineProperty(exports, "createUpdateSchema", { enumerable: true, get: function () { return utils_1.createUpdateSchema; } });
Object.defineProperty(exports, "paginationSchema", { enumerable: true, get: function () { return utils_1.paginationSchema; } });
Object.defineProperty(exports, "validatePagination", { enumerable: true, get: function () { return utils_1.validatePagination; } });
Object.defineProperty(exports, "AppLogger", { enumerable: true, get: function () { return utils_1.AppLogger; } });
Object.defineProperty(exports, "createLogger", { enumerable: true, get: function () { return utils_1.createLogger; } });
Object.defineProperty(exports, "initializeLogger", { enumerable: true, get: function () { return utils_1.initializeLogger; } });
Object.defineProperty(exports, "getLogger", { enumerable: true, get: function () { return utils_1.getLogger; } });
Object.defineProperty(exports, "HealthMonitor", { enumerable: true, get: function () { return utils_1.HealthMonitor; } });
Object.defineProperty(exports, "createRequestLogger", { enumerable: true, get: function () { return utils_1.createRequestLogger; } });
Object.defineProperty(exports, "createErrorLogger", { enumerable: true, get: function () { return utils_1.createErrorLogger; } });
//# sourceMappingURL=index.js.map